FROM node:alpine
RUN mkdir -p /tmp
COPY package.json /tmp
RUN cd /tmp && npm install
ENV PATH /tmp/node_modules/.bin:${PATH}

WORKDIR /app
COPY . .
CMD rm -rf node_modules && ln -s /tmp/node_modules/ node_modules && npm run dev